export const Titles: string[] = [
  "Lorem ipsum dolor sit amet", 
  "ut eum movet putent persequeri",
  "In quo idque saepe', et pro meliu",
  "Utamur Cum sint sale a",
  "No sed lobortis perpetua tractato",
  "Ex eam nominati philosophia", 
  "Meis vidit omnis ei si",
  "Habemus appareat consequat ut se",
  "Te sed lorem hendrerit", 
  "Posse oratio quo t",
  "Ei ipsum primis quo", 
  "At vix graeco imperdiet temporibu",
  "At eam augue corrumpi",
  "Cum in discere molestiae", 
  "Vim dolor mucius scaevola ea", 
  "Quo dolorum interesset c",
  "Sed at case nusquam singuli",
  "Vim ei accusata referrentur", 
  "Mea id volumus ocurreret", 
  "Nam ex invenire deterruisset", 
  "Ne has prima postulant salutand",
  "Augue vivendo volumus vis in", 
  "Ponderum consequat intellegam eu eam", 
  "His in scaevola platonem dissentiet", 
  "Falli simul vulputate usu eu", 
  "ex tation audire posidonium mel", 
  "Per in deserunt percipitur", 
  "Ei conceptam reformidans pro", 
  "Malorum sapientem maluisset vix no", 
  "Delectus accusamus id usu", 
  "Per eu copiosae patrioque interesset", 
  "An utroque facilisis philosophia si",
  "Agam oratio commodo eu vis", 
  "At nonumes offendit sadipscing eam", 
  "Augue impetus eum ex", 
  "Oblique officiis et eos", 
  "Id case petentium voluptatum per", 
  "Vel perfecto omittantur cu", 
  "Eos erroribus cotidieque at", 
  "In vel purto paulo facilisi", 
  "Est suas agam ei", 
  "Torquatos complectitur eu per", 
  "Saperet invidunt no iu",
  "At autem solet suscipit eam", 
  "Ei prima abhorreant pro", 
  "Dicam possit vel id", 
  "Qquas ridens accusata sea ad", 
  "In usu fastidii percipit tincidunt", 
  "Ad vel alterum apeirian complectitur", 
  "Usu id accusata postulant", 
  "Ea has iriure legimus", 
  "Quo in pertinax conclusionemque", 
  "Duis debitis his no", 
  "Eum ei quod oportere", 
  "Ei mel justo malorum definitiones", 
  "Per aeque everti u",
];

export const Types: string[] = [
  'Type 1', 'Type 2', 'Type 3', 'Type 4'
];

export interface IItem {
  title: string,
  types: string[]
};



